//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Eventos.IO.Domain.Resources.Evento {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Erros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Erros() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS.Eventos.IO.Domain.Resources.Evento.Erros", typeof(Erros).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de inicio não deve ser menor do que a data atual..
        /// </summary>
        internal static string DATAINICIO_MAIOR_DATAATUAL {
            get {
                return ResourceManager.GetString("DATAINICIO_MAIOR_DATAATUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de inicio deve ser menor que a data final do evento..
        /// </summary>
        internal static string DATAINICIO_MAIOR_DATAFINAL {
            get {
                return ResourceManager.GetString("DATAINICIO_MAIOR_DATAFINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do evento precisa ter entre 2 e 150 caracteres..
        /// </summary>
        internal static string NOME_LENGTH {
            get {
                return ResourceManager.GetString("NOME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do evento precisa ser fornecido..
        /// </summary>
        internal static string NOME_NULL {
            get {
                return ResourceManager.GetString("NOME_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O evento nao deve possuir um endereço pois é online..
        /// </summary>
        internal static string ONLINE_COM_ENDERECO {
            get {
                return ResourceManager.GetString("ONLINE_COM_ENDERECO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O evento deve ter um endereço..
        /// </summary>
        internal static string PRESENCIAL_SEM_ENDERECO {
            get {
                return ResourceManager.GetString("PRESENCIAL_SEM_ENDERECO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor precisa ser 0, pois o evento é gratuito..
        /// </summary>
        internal static string VALOR_GRATUITO {
            get {
                return ResourceManager.GetString("VALOR_GRATUITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor precisa estar entre 1.00 e 50.000..
        /// </summary>
        internal static string VALOR_MIN_MAX {
            get {
                return ResourceManager.GetString("VALOR_MIN_MAX", resourceCulture);
            }
        }
    }
}
